### ISSUE TITLE
Compile error : can't find core.clj

### ISSUE THREAD

**Issue by guruma** [lispkorea/lispkorea#1]
git clone 한 다음 lein run하면

"Compilation failed: java.io.IOException: 지정된 경로를 찾을 수 없습니다, compiling:(lispkorea/core.clj:1)" 에러 메세지 발생.

project.clj에서 :main lispkorea.server 추가하고 lein run하면

"Compilation failed: java.io.IOException: 지정된 경로를 찾을 수 없습니다, compiling:(lispkorea/server.clj:1)" 에러 메세지 발생.

**Comment by longfin** [comment]
<code>lein repl</code>이나 <code>lein ring server</code>는 동작하시나요?

**Comment by guruma** [comment]
같은 결과를 내고 있습니다. ^^;

2012/9/18 Seong Won Mun notifications@github.com

**Comment by longfin** [comment]
<code>classes</code> 디렉토리를 지우고나니 저도 재현되네요.

https://github.com/technomancy/leiningen/issues/769 와 연관된 문제로 보입니다. <code>:eval-in-leiningen</code>을 대체할만한 방법을 찾아야할 것 같습니다.
